# Generated by Django 5.0.4 on 2024-04-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="auth_provider",
            field=models.CharField(default="email", max_length=255),
        ),
    ]
