# Generated by Django 5.0.4 on 2024-04-15 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="income",
            old_name="category",
            new_name="source",
        ),
    ]
